### ISSUE TITLE
Casting subject

### ISSUE THREAD

**Issue by Lakitna** [Lakitna/cypress-commands#22]
# Type of feature

- [x] Add a new command
- [ ] Extend a default Cypress command
- [ ] Change a Cypress-commands command
- [ ] Other

# What do you want to accomplish?

Initial context: https://github.com/cypress-io/cypress/issues/630#issuecomment-504996592

The ability to cast values to different primitives to allow us to write something like

```javascript
cy.get(...)
  .text()
  .castSubjectToANumberInThisCommand()
  .should('be.above', 1);
```

# Why?

To simplify reading your tests. This would replace code like

```javascript
cy.get(...)
  .text()
  .then((val) => Number(val))
  .should('be.above', 1);
```

This code isn't bad, but it can be a bit scary for some.

# Describe possible implementations

A few possibilities at this point:

## Command per cast

```javascript
cy.wrap('007')
  .number()
  .should('equal', 7);

cy.wrap(123)
  .string()
  .should('equal', '123');

cy.wrap('foo')
  .array()
  .should('equal', ['foo']);
```

These might be better when named `.asNumber()`, `.asString()` and `.asArray()`. Otherwise you would get confusing chains like `cy.get(...).text().number()`.

## Wrapper commands that casts

Example for the `.text()` command: Add a new `.number()` command that will retrieve the numeric contents of a subject element.

```javascript
cy.get('.mrBond')
  .number()
  .should('equal', 7);
```

On a technical level this would essentially contain `.text().then((n) => Number(n))`.

## Generic cast command

```javascript
cy.wrap('007')
  .cast('number')
  .should('equal', 7);
```

## Cast in existing commands based on upcoming assertions

For the `.attribute()` command I made a way to gather the upcoming assertions with decent stability. This is very hacky and we probably shouldn't rely on that if we can help it.

```javascript
cy.get('.mrBond')
  .text()
  .should('equal', 7);
```

## Cast in existing commands based on an option

```javascript
cy.get('.mrBond')
  .text({ cast: 'number' })
  .should('equal', 7);
```

# Additional context

The conversation starting at this comment https://github.com/cypress-io/cypress/issues/630#issuecomment-504996592

**Comment by Lakitna** [comment]
@dialex Could you please share your opinion regarding these options?

**Comment by dialex** [comment]
Of course, it's an honour. (btw, your issue is very organised, reads like a documentation page 👏)

I really like the idea of `.asNumber()`, because intuitively you know there's a cast involved. I would be very happy to read something like `cy.get(...).asNumber().should('be.above', 1)`. That covers my need.

**Comment by Lakitna** [comment]
I agree that `.asNumber()` and its siblings are probably one of the most straightforward ways. They are also easy to understand when reading tests without breaking the reader's flow.

Do you think some people might confuse it with `.as('alias')`? It sounds the same but is used for an entirely different purpose, so it might be confusing.

```javascript
cy.get('.mrBond')
  .text()
  .asNumber()
  .as('britishSpy');

// ...

cy.get('@britishSpy')
  .should('equal', 7);
```

An alternative name could be `.toNumber()`, but that's an abstraction where we're using the language of casting. Not all users will know what that is.

**Comment by dialex** [comment]
You have a point, `.to` avoids confusing with Cypress' aliasing ✅

**Comment by Lakitna** [comment]
So these would be the commands:

### Number

```javascript
// Subject is string
cy.wrap('007')
  .toNumber()
  .should('be.below', 8);
```

```javascript
// Subject is arary of strings
cy.wrap(['7', '6', '5'])
  .toNumber()
  .should('deep.equal', [7, 6, 5]);
```

```javascript
// Subject is a number (do nothing)
cy.wrap(123)
  .toNumber()
  .should('equal', 123);
```

| option | default | values | description |
|----|----|----|----|
| `log` | `true` | `true` `false` |  |
| `timeout` | `defaultCommandTimeout` | `{number}` |  |

#### Fails on

Unable to cast to number:
- `typeof subject === undefined`
- `typeof subject === 'object'`
- `Array.isArray(subject[n])` (array is allowed on top level, nested arrays result in error)
- `isNaN(Number(subject))`

-----------------------

### Array

```javascript
// Input is a non-iterable
cy.wrap('Hey, listen!')
  .toArray()
  .should('deep.equal', ['Hey, listen!'])
  .each((value) => {
    // ...
  });
```

```javascript
// Subject is an iterable (do nothing)
cy.wrap(['Hey, listen!'])
  .toArray()
  .should('deep.equal', ['Hey, listen!']);
```

| option | default | values | description |
|----|----|----|----|
| `log` | `true` | `true` `false` |  |
| `timeout` | `defaultCommandTimeout` | `{number}` |  |

#### Fails on

*Nothing?*

-----------------------

### String

```javascript
// Subject is number (using `String()`)
cy.wrap(123)
  .toString()
  .should('equal', '123');
```

```javascript
// Subject is array (using `Array.toString()`)
cy.wrap(['foo', 123])
  .toString()
  .should('equal', 'foo,123');
```

```javascript
// Subject is object (using `JSON.stringify()`)
cy.wrap({ 'foo': 123 })
  .toString()
  .should('equal', '{"foo":123}');
```

Always use `subject.toString()` when available.

| option | default | values | description |
|----|----|----|----|
| `log` | `true` | `true` `false` |  |
| `timeout` | `defaultCommandTimeout` | `{number}` |  |

#### Fails on

*Nothing?*

**Comment by Lakitna** [comment]
While working on `.toArray()` I started thinking more and more at it's probably better to make the generic cast command `.to()` instead.

```javascript
cy.wrap('007')
  .to('number')
  .should('equal', 7);
```

```javascript
cy.wrap(123)
  .to('string')
  .should('equal', '123');
```

```javascript
cy.wrap(123)
  .to('array')
  .should('deep.equal', [123]);
```

It would need a nice error message when the input is not `number`, `string` or `array`.

I'll think about this more later.

**Comment by dialex** [comment]
> It would need a nice error message when the input is not number, string or array.

Exactly, at least that. Even better would be if you added autocomplete documentation through `/** ... */`, that way the dev knows what to use without getting the error.

**Comment by Lakitna** [comment]
Yes, adding types is standard procedure and in this case, will dictate the supported cast targets.

I did have a brainwave while trying to sleep last night that may make `.to('array')` obsolete, though I'm not sure it'll work yet. Just so I don't forget: Return primitives wrapped in a jQuery object instead of a primitive. This will reduce the number of commands and thus help with reliability.

**Comment by Lakitna** [comment]
Will be part of 0.3.0
https://github.com/Lakitna/cypress-commands/milestone/2
