### ISSUE TITLE
Add `whitespace` option to `attribute` command

### ISSUE THREAD

**Issue by x-yuri** [Lakitna/cypress-commands#28]
# Type of feature

- [ ] Add a new command
- [ ] Extend a default Cypress command
- [x] Change a Cypress-commands command
- [ ] Other

# What do you want to accomplish?
```js
cy.get('img').attribute('src', {whitespace: 'simplify'})
    .should('eq', 'http://host/some/path');
```

# Why?
Because with `cy.wrap($('<img src=" http://host/some/path">'))` or something it fails.

# Describe possible implementation
https://github.com/Lakitna/cypress-commands/blob/develop/src/text.js#L53-L57
plus `trim()`

**Comment by Lakitna** [comment]
I did think about adding this, but figured it would never be necessary
since trimable whitespace shouldn't really be a thing in attributes. Though
it can't hurt to add the whitespace option with default `keep`.

I'm curious why your your specific situation needs this. What's the exact
output of your `attribute` command?

**Comment by x-yuri** [comment]
The template goes like this:

```html
                    {% for p in photos  %}
                        <li>
                            <img src="
                                {% if forloop.first %}
                                    {{ p.file_l.url }}
                                {% else %}
                                    {{ p.file_s.url }}
                                {% endif %}
                            ">
                    {% endfor %}
```

I believe that answers your question. But feel free to ask further ones.

**Comment by Lakitna** [comment]
Ah that makes a lot of sense then.

I'll add the whitespace option to the command, but before I do I'll have to
dive into the html specs to determine what the default value should be. I
want to know how html does this. I'm guessing `simplify` but that would be
a breaking change as its essentially `keep` right now.

But before any of that I'll need to get back from holiday :)

**Comment by Lakitna** [comment]
I've taken a look at the HTML spec and found this about what is allowed in attribute values

> Attribute values are a mixture of text and character references, except with the additional restriction that the text cannot contain an ambiguous ampersand.

https://www.w3.org/TR/html52/syntax.html#attribute-values

There are no other relevant things in the spec for this situation.

There is no mention of whitespace handing in the spec, leading me to believe that whitespace should be irrelevant as much as possible. I think setting the default `whitespace: 'simplify'` would be the best fit here. Even though that would make this a breaking change.

**Comment by x-yuri** [comment]
Sorry for the late reply. I'd make `keep` the default, since it seems like what most people would generally want. And in case they wouldn't, they can always specify `whitespace: 'simplify'`. If a lot of people would come and complain about it, you can always change the default.

**Comment by Lakitna** [comment]
Hmm good point. I'll make it `keep` for now.
