### ISSUE TITLE
Updates for Cypress@4.0.0

### ISSUE THREAD

**Issue by Lakitna** [Lakitna/cypress-commands#38]
All tests still pass in both GUI and CLI mode, but some things will have to be updated for future compatibility.

**Comment by singh-manjot** [comment]
Hi! Can we please update the devDependencies for the plugin? The current dependencies (^3.8.2) for this plugin conflict with our Cypress version (^4.0.0). Thanks!

**Comment by Lakitna** [comment]
How does it conflict? I've run the tests and everything passes with 4.0.0 which is why I did not think I would have to do this quickly. The change in this issue was supposed to only be the dependency version.

**Comment by singh-manjot** [comment]
Apologies @Lakitna ! I just re-tried adding the plugin and turns out it works just fine with the new version. Thanks!
