### ISSUE TITLE
Add `timeout` option to `then`

### ISSUE THREAD

**Issue by m4dc4p** [Lakitna/cypress-commands#40]
The default `then` command accepts a `timeout` option. Can you extend your types to mirror (or import) the cypress types? In 4.1.0, this is the `Timeoutable` interface.

BTW I love this plugin. Thank you for writing it!

**Comment by Lakitna** [comment]
Huh, I've taken a look at it and it looks like I've totally missed `then()` being timeoutable.. It's been like that for at least three years according to the documentations git blame https://github.com/cypress-io/cypress-documentation/blame/develop/source/api/commands/then.md

I've also found a test I copied from the Cypress repo testing this exact thing so I'm confident that my `then()` is also timeoutable.

I'll also take this chance to get my `then()` types more in line with the defaults

**Comment by m4dc4p** [comment]
I was still able to use `retry` and `timeout`, even w/o the correct types, but I'm not quite sure how. Thanks for looking at it!

**Comment by Lakitna** [comment]
Released in 1.1.0 :)
