### ISSUE TITLE
text() command adds spaces if element's content has <wbr> tags inside

### ISSUE THREAD

**Issue by OlenaVakulenko** [Lakitna/cypress-commands#46]
# Describe the bug
`text()` commands adds spaces if element's content has `<wbr>` tags inside

# To Reproduce

HTML to reproduce:
`<a href="/cell_phones/mobile_phone_samsung_a207f_galaxy_a20s_32_duos_red_sm-a207fzrdsek.html" class="product-name">Мобильны<wbr>й телефон Samsung A207F Galaxy A20s/32 Duos Red (SM-A207FZRD<wbr>SEK)</a>`

`cy.get('.product-name').text()` 
yields
`Мобильны й телефон Samsung A207F Galaxy A20s/32 Duos Red (SM-A207FZRD SEK)`

# Expected behavior
`cy.get('.product-name').text()` 
yields
`Мобильный телефон Samsung A207F Galaxy A20s/32 Duos Red (SM-A207FZRDSEK)`

# Versions and such:
 - OS: Windows 8.1
 - Cypress version: 4.12.1
 - Cypress browser: Chrome
 - Cypress-commands version: 1.1.0

# Additional context
The native approach `cy.get('.product-name').invoke('text')` gives the expected result of `Мобильный телефон Samsung A307F Galaxy A30s/32 Duos White (SM-A307FZWUSEK)`

**Comment by Lakitna** [comment]
Oh, good one. I am condensing all whitespace to a single space. `<wbr>` results in a zero-width space, which `.text()` wrongly considers being whitespace in this case.

To fix this I'll have to get rid of all zero-width spaces before doing the current whitespace condensing.
