### ISSUE TITLE
Cannot get value in .text() from input

### ISSUE THREAD

**Issue by markbeaman44** [Lakitna/cypress-commands#48]
# Describe the bug
I'm trying to obtain a value/text within the <input> via .text(), it always brings back an empty string - but looking at the logs it contains a jQuery and within it, it contains value="MY_VALUE".
I did via <div with .text() and it worked, I just have an issue with <input - is there away to obtain this from the results within the jQuery. I did the following things but didnt work.
I'm not sure if this is a bug or due to my lack of understanding please help :)

# Code
`const getToken = cy.get('#copiedToken').text()` - empty string

`const getToken = cy.get('#copiedToken').text()
let bla = getToken[0].value` - this always gives undefined value - but in jQuery it shows my text in the value part

`cy.get('#copiedToken').text({ depth: Infinity }).then(($info) => {
    cy.log($info)
  })` - this gives empty string

# Screenshots
<img width="1438" alt="Screenshot 2020-08-12 at 15 01 36" src="https://user-images.githubusercontent.com/30801986/90032043-da6d2a00-dcb5-11ea-8244-f31132a4e1ac.png">
<img width="490" alt="Screenshot 2020-08-12 at 15 01 47" src="https://user-images.githubusercontent.com/30801986/90032048-db05c080-dcb5-11ea-94cc-dacafea19ed9.png">

# Versions and such:
 - OS: Mac
 - "cypress": "^3.8.3",
 - "cypress-commands": "^1.1.0",

# Additional context

**Comment by Lakitna** [comment]
It's actually a thing of jQuery that many before you have run into. In short, `.text()` collects what's inside of an element so you can get the following:

```html
<div>I am inside the div element</div>
```
```javascript
cy.get('div')
  .text()
  .should('equal', 'I am inside the div element');
```

But the `<input>` element does not store its value inside itself but as an attribute instead.

```html
<input value="It looks like I'm inside the input field, but I'm an argument!" />
```

To get this value out you can use `.attribute()` instead [[`.attribute()` documentation]](https://github.com/Lakitna/cypress-commands/blob/develop/docs/attribute.md)

```javascript
cy.get('input')
  .attribute('value')
  .should('equal', "It looks like I'm inside the input field, but I'm an argument!");
```

Or alternatively, you can do it without `.attribute()`:

```javascript
cy.get('input')
  .should((input) => {
    expect(input.val()).to.equal("It looks like I'm inside the input field, but I'm an argument!");
  });
```

**Comment by markbeaman44** [comment]
Thanks for your help - both `.attribute('value')` and `input.val()` worked for me - I need to learn more about jQuery :)
