### ISSUE TITLE
cy.get(element).text() seems to be not working

### ISSUE THREAD

**Issue by antonm1989** [Lakitna/cypress-commands#52]
# Changes should be made to

- [ ] General documentation (ex. README.md)
- [ ] Command documentation (ex. docs/then.md)
- [ ] Command type definitions / Intellisense

# Describe the improvement
I can't get text() command working - it doesn't return text as a string.

# Why?
Why do you think there should be a change?

# Possible improvements
How can we improve it? You probably don't need to answer this question if you are writing the improvements yourself.

# Additional context

**Comment by Lakitna** [comment]
`text()` is not supposed to return a string, it yields a string instead. I do see that I didn't add specific examples for this in the docs. 

From your description I think you're using the command like this:

```
const foo = cy.get(...).text()
expect(foo).to.equal('something')
```

Using any command this way is not the Cypress way. Try using the command like this instead:

```
cy.get(...)
  .text()
  .should('equal', 'something')
```

**Comment by antonm1989** [comment]
Hey! Yes, my code looks like this:
`cy.get($emailField).text()`

When I try it this way I can successfully assert my text:
```
cy.get(this.locators.emailField).then(($text) => {
                        myText = $text.text()
```
But the problem I have is how can I get that text value outside of that function? For example, I need to save that text to some variable and then access it somewhere else in a different class/function?

**Comment by cubanx** [comment]
So this is a year late but maybe it will help someone else.

What you’re looking for is `cy.wrap()`

https://docs.cypress.io/api/commands/wrap

**Comment by Lakitna** [comment]
Closing as this is described in the Cypress docs: https://docs.cypress.io/guides/core-concepts/variables-and-aliases#Return-Values
