### ISSUE TITLE
Issues with Cypress 6.4 with fixes

### ISSUE THREAD

**Issue by JohnAtFenestra** [Lakitna/cypress-commands#54]
# Describe the bug
I pulled down the code base and updated Cypress from 5.x to 6.x. I found two failing tests, one relatively simple issue and one I believe may be a test which has been removed from the Cypress suite.

# To Reproduce
Delete `node_modules` and `package-lock.json`
Change Cypress version in `package.json` to `^6.0.0`

Reinstall

# Expected behavior
All tests run green

# Screenshots

# Versions and such:
 - OS: Ubuntu 20.04
 - Cypress version: 6.4
 - Cypress browser: 
 - Cypress-commands version: 

# Additional context

There are two failing tests. 

## Failure in then

`then.js`

Line 320
```javascript
    expect(err.message).to.equal('Timed out retrying: expected 5 to equal 4');
```
Fails because the message from Cypress has changed to include the number of millseconds. Changing to

```javascript
    expect(err.message).to.contain('expected 5 to equal 4');
```
Causes the test to pass and verifies the intended result.

## Cypress runner failing on  `copied/request.js`

here is a folder under cypress integration, `copied`. It contains one spec, `request.js`. This variant fails the test 
`is deprecated but does not fail even on 500 when failOnStatus=false`

The full error is:

```
cy.request() failed on:

http://localhost:1234/foo

The response we received from your web server was:

  > 500: undefined

This was considered a failure because the status code was not 2xx or 3xx.

If you do not want status codes to cause failures pass the option: failOnStatusCode: false
```

**Comment by Lakitna** [comment]
Closed by #61
