### ISSUE TITLE
Attribute Command not working

### ISSUE THREAD

**Issue by cubanx** [Lakitna/cypress-commands#60]
# Describe the bug
When you try to use the `.attribute` command, you get:
`queue.filter is not a function`

It looks like Cypress removed the `.filter` method in version 8.3. I played with this locally and it *seems* to work if I just switch it to use `.find`

However, I think I'm missing something with the `invoked` 

# To Reproduce
Write any test that uses the `.attribute` command

# Expected behavior
The `.attribute` command should not throw an error.

# Versions and such:
 - OS: Windows 10
 - Cypress version: > 8.2
 - Cypress browser: Any
 - Cypress-commands version:  1.1.0

# Additional context
The problem line is here:
https://github.com/Lakitna/cypress-commands/blob/08adc6c31323e581c3d44e749f8327a52cb6365a/src/utils/commandQueue.js#L11

I cannot seem to find any info on the `.filter` method on Cypress docs or in the issues list.

I've seen the problem in Cypress 8.3 and 8.3.1

I can try to do a PR to fix it if that would help.

Thanks!

Ricardo Diaz

**Comment by Lakitna** [comment]
I ran into this one too myself. In 8.3.0 they updated an internal thing that I depended on to make retry work as expected.

I need this fix myself too ;) Though I am very busy this month so please bear with me.

**Comment by Lakitna** [comment]
> However, I think I'm missing something with the invoked

The invoked bit is essentially a way to mark a command in the command queue so that it can be found again later on. We need this for the retry behavior of `.attribute`. Specifically when you do something like:

```javascript
cy.get(<multiple divs>)
  .attribute('class')
  .should('not.exist');
```

I managed to fix it with `queue.get().filter(...)` which is a bit more flexible than `find` is ;)
