### ISSUE TITLE
How to use this

### ISSUE THREAD

**Issue by dkoudrinhc** [Lakitna/cypress-commands#64]
How do I actually use these commands in my test files? I don't understand, the documentation tells me some random steps but actually invoking say .text() function doesn't work.

**Comment by Lakitna** [comment]
After you've installed `cypress-commands` as described in [the main readme file](https://github.com/Lakitna/cypress-commands#installation) you can use the `.text()` command as described in [the `.text()` command documentation](https://github.com/Lakitna/cypress-commands/blob/develop/docs/text.md).

For example:

```html
<div>Hello, world!</div>
```

```javascript
cy.get('div').text().should('equal', 'Hello, world!');
```

**Comment by dkoudrinhc** [comment]
.text() already exists on the cy.get, so that wouldn't be adding anything.

**Comment by Lakitna** [comment]
`.text()` is not a default command. The fact that it already exists for you means that you have successfully installed `cypress-commands`. You can simply start using it now.
