### ISSUE TITLE
Update plugin to be compatible with Cypress 10

### ISSUE THREAD

**Issue by admah** [Lakitna/cypress-commands#69]
# Type of feature

- [ ] Add a new command
- [ ] Extend a default Cypress command
- [ ] Change a Cypress-commands command
- [x] Other

Hello 👋 I'm writing on behalf of the Cypress DX team. We wanted to notify you that some changes may need to be made to this plugin to ensure that it works in Cypress 10. 

For more information, here is our [official plugin update guide](https://cypressdx.notion.site/Cypress-10-Plugin-Update-Guide-7474129c5a3b4cc7b969d1934c5844a0).

**Comment by Lakitna** [comment]
@admah Thanks for the notification :)

I've worked on it a bit and ran into one issue. The rest just needs a bit more attention to make all tests pass :)

The extended `cy.request()` in this repo supports the configuration parameter `requestBaseUrl`. Details https://github.com/Lakitna/cypress-commands/blob/develop/docs/request.md

The functionality still works, but I can't find a way to extend the types of the cypress config (those used by `defineConfig()`). Can these types be extended or should I create an issue for this?

**Comment by admah** [comment]
@Lakitna I believe you're going to want to leverage the new `setupNodeEvents` function [outlined here](https://deploy-preview-4186--cypress-docs.netlify.app/api/plugins/configuration-api#Usage) to add the `requestBaseUrl` config option.

**Comment by Lakitna** [comment]
It's not an issue with putting the value into the config object. That works just fine and doesn't even need the `setupNodeEvents` thing :)

It's purely a typing issue. I could safely ignore it before, but now Cypress supports `cypress.config.ts` so I need to get them working properly.

<img width="668" alt="image" src="https://user-images.githubusercontent.com/22448210/171347450-7963d9f6-b2ad-41ca-96df-faa7f704f4c8.png">

<img width="503" alt="image" src="https://user-images.githubusercontent.com/22448210/171349395-6d9cb877-5867-4530-b20f-22f6e2629ba8.png">

Looking into the types, it looks like I'd have to add `requestBaseUrl` to `Cypress.ResolvedConfigOptions<ComponentDevServerOpts = any>`, but it won't let me extend that interface :(

**Comment by Lakitna** [comment]
@admah Got any insights into the type definition thing? It's the only thing preventing me from releasing 3.0.0 right now.

**Comment by admah** [comment]
@Lakitna I left a comment on your PR [here](https://github.com/Lakitna/cypress-commands/pull/70/files#r890208538).
