### ISSUE TITLE
TypeScript types for cy.then

### ISSUE THREAD

**Issue by jkdowdle** [Lakitna/cypress-commands#8]
# Type of feature

- [ ] Add a new command
- [ ] Extend a default Cypress command
- [ ] Change a Cypress-commands command
- [x] Other

# What do you want to accomplish?
I am using Cypress with typescript and would love to use the retry feature of your package 

# Why?
A short description of why you want to accomplish the things mentioned above.
however I am getting errors related to types. 

`
Argument of type '{ retry: boolean; }' is not assignable to parameter of type 'Partial<Timeoutable>'.
  Object literal may only specify known properties, and 'retry' does not exist in type 'Partial<Timeoutable>'.ts(2345)
`

# Describe possible implementations

I am not quite sure how, but I think we need to overwrite the default cypress then typings to include this packages options.

# Additional context
Add any other context or screenshots about the request here.

**Comment by Lakitna** [comment]
Type definitions are on the planning, I'll move them forward for you.

**Comment by jkdowdle** [comment]
@Lakitna 

Thanks a ton!

**Comment by Lakitna** [comment]
I am not a Typescript user myself. Can you please validate the definitions I added?

**Comment by jkdowdle** [comment]
Sure!. Have you already published them?

**Comment by Lakitna** [comment]
Yes, see #9 
The branch is called `Type-definitions-for-then-command`. You should be able to pull the branch and make your tsconfig point to that.

**Comment by jkdowdle** [comment]
Ok, so assuming that I did it correctly, this is what I found. 

I have two errors coming up on a basic test that I pulled from the repos tests.

`TS7006: Parameter 'subject' implicitly has an 'any' type`
`TS2560: Value of type '(subject: any) => any' has no properties in common with type '{ log?: boolean; retry?: boolean; }'. Did you mean to call it?`

Here is my test.

```
describe('retryability', () => {
  it('retries until the upcoming assertion passes', () => {
    let c = 0
    cy.then(
      subject => {
        ++c
        return subject
      },
      { retry: true, bilbo: false }
    )
  })
})
```

**Comment by Lakitna** [comment]
I've made Subject explicitly `any` (I think) and added types for reversing the order of `options` and `fn`. Can you try again?

**Comment by jkdowdle** [comment]
That looks like it did the trick! Thank you so much! 

I tried both 
```cy.then({ retry: true }, () => ++c)```
```cy.then(() => ++c, { retry: true })```

Both passed and gave me the expected warnings. 

```
describe('retryability', () => {
  it('retries until the upcoming assertion passes', () => {
    let c = 0
    cy.then(() => ++c, { retry: true })
  })
})
```

**Comment by Lakitna** [comment]
Awesome! I'll go ahead and merge it then.

I'll include it in the 0.1.0 release which will also include #4 which I plan to finish up somewhere tonight or tomorrow.
